### ISSUE TITLE
Date/time for planner

### ISSUE THREAD

**Issue by nsdrozario** [nsdrozario/programming-club-creations#14]
Implement `planner/date_util.js`

**Comment by ptr-dodge** [comment]
implemented, but still needs work to get rid of '13 PM' cause we don't need that

**Comment by JY1106** [comment]
13 PM Issue resolved
How about 12am should go to the top like the image below? As 12am (0:00) is next day, I think 12am should start a day, not 1am.
![image](https://user-images.githubusercontent.com/77516631/118343887-5b28b300-b4e0-11eb-8356-91ce68e3f5bb.png)

**Comment by ptr-dodge** [comment]
will do

**Comment by ptr-dodge** [comment]
13PM fixed, changed to 12AM at beginning

**Comment by nsdrozario** [comment]
Very impressive! Will mark as fixed.
