### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by nsdrozario** [nsdrozario/programming-club-creations#4]
- [x] Readme created

If you need to learn Markdown styling, consult [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/)

**Comment by loudelmar** [comment]
hi! can u asign it to me? thx

**Comment by nsdrozario** [comment]
Hello,
While your interest is appreciated, this group and its repository are meant for educational purposes of its own members, as it is a club. Unfortunately, I must decline your request. Thank you anyway and have a nice day!
